# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/prompt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/prompt.proto\x12\x02pb\" \n\x10GetPromptRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x11GetPromptResponse\x12\x0e\n\x06prompt\x18\x01 \x01(\t2I\n\rPromptService\x12\x38\n\tGetPrompt\x12\x14.pb.GetPromptRequest\x1a\x15.pb.GetPromptResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.prompt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _globals['_GETPROMPTREQUEST']._serialized_start=26
  _globals['_GETPROMPTREQUEST']._serialized_end=58
  _globals['_GETPROMPTRESPONSE']._serialized_start=60
  _globals['_GETPROMPTRESPONSE']._serialized_end=95
  _globals['_PROMPTSERVICE']._serialized_start=97
  _globals['_PROMPTSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
