// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/prompt.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPromptRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPromptRequest) Reset()         { *m = GetPromptRequest{} }
func (m *GetPromptRequest) String() string { return proto.CompactTextString(m) }
func (*GetPromptRequest) ProtoMessage()    {}
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcffa97217bf164e, []int{0}
}

func (m *GetPromptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPromptRequest.Unmarshal(m, b)
}
func (m *GetPromptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPromptRequest.Marshal(b, m, deterministic)
}
func (m *GetPromptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPromptRequest.Merge(m, src)
}
func (m *GetPromptRequest) XXX_Size() int {
	return xxx_messageInfo_GetPromptRequest.Size(m)
}
func (m *GetPromptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPromptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPromptRequest proto.InternalMessageInfo

func (m *GetPromptRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetPromptResponse struct {
	Prompt               string   `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPromptResponse) Reset()         { *m = GetPromptResponse{} }
func (m *GetPromptResponse) String() string { return proto.CompactTextString(m) }
func (*GetPromptResponse) ProtoMessage()    {}
func (*GetPromptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcffa97217bf164e, []int{1}
}

func (m *GetPromptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPromptResponse.Unmarshal(m, b)
}
func (m *GetPromptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPromptResponse.Marshal(b, m, deterministic)
}
func (m *GetPromptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPromptResponse.Merge(m, src)
}
func (m *GetPromptResponse) XXX_Size() int {
	return xxx_messageInfo_GetPromptResponse.Size(m)
}
func (m *GetPromptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPromptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPromptResponse proto.InternalMessageInfo

func (m *GetPromptResponse) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPromptRequest)(nil), "pb.GetPromptRequest")
	proto.RegisterType((*GetPromptResponse)(nil), "pb.GetPromptResponse")
}

func init() { proto.RegisterFile("proto/prompt.proto", fileDescriptor_bcffa97217bf164e) }

var fileDescriptor_bcffa97217bf164e = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x28, 0xca, 0xcf, 0x2d, 0x28, 0xd1, 0x03, 0x73, 0x84, 0x98, 0x0a, 0x92, 0x94,
	0xd4, 0xb8, 0x04, 0xdc, 0x53, 0x4b, 0x02, 0xc0, 0xc2, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x42, 0x5c, 0x2c, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x36, 0x97, 0x20, 0x92, 0xba, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e,
	0x36, 0x88, 0x81, 0x50, 0xa5, 0x50, 0x9e, 0x91, 0x27, 0x17, 0x2f, 0x44, 0x65, 0x70, 0x6a, 0x51,
	0x59, 0x66, 0x72, 0xaa, 0x90, 0x05, 0x17, 0x27, 0x5c, 0xb7, 0x90, 0x88, 0x5e, 0x41, 0x92, 0x1e,
	0xba, 0xa5, 0x52, 0xa2, 0x68, 0xa2, 0x10, 0x2b, 0x9c, 0xd8, 0xa2, 0x58, 0xf4, 0xf4, 0x0b, 0x92,
	0x92, 0xd8, 0xc0, 0x4e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xdd, 0x9a, 0xb7, 0xc8,
	0x00, 0x00, 0x00,
}
